backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

local_backend: true

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - name: "home"
        label: "Página principal"
        file: "content/home.md"
        fields:
          - { label: "Título hero", name: "title", widget: "string" }
          - { label: "Subtítulo hero", name: "subtitle", widget: "text" }
          - { label: "Texto principal (Quiénes somos)", name: "body", widget: "markdown" }
          - { label: "Texto botón principal", name: "hero_button_primary", widget: "string" }
          - { label: "Texto botón secundario", name: "hero_button_secondary", widget: "string" }
